name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@88425854a36845f9c881450d9660b5fd46bee142
      - name: Build with Gradle
        run: ./gradlew build
